#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Load NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion#

alias dev="cd ~/Development"
alias ..="cd .."

alias emacs="emacs -nw"

# Add GO to PATH
export GOPATH="/home/lampd1/Development/go"
export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin

# I think some pip3 user space files are landing here
export PATH=$PATH:$HOME/.local/bin
